### ISSUE TITLE
Add UPROPERTY meta = ( ValidEnumValues = "YourEnumValue1, YourEnumValue2" )

### ISSUE THREAD

**Issue by 0ne3y3** [benui-dev/UE-Specifier-Docs#11]
Missing this meta specifier. It filters enum values, simply.

The example below is for my personal project, but there is also a use case in the file MaterialExpressionShadingModel.h. Where they filter out shading models we can't use with this material node.

```
/**
* Enum for part of the body
*/
UENUM( BlueprintType )
enum class EBodyPartType : uint8
{
	MainBody,
	Eye,
	Head,
	Hair,
	Torso,
	Arms,
	Hands,
	Legs,
	Feet,
	Accessory,
	Special
};

/**
 * UModularSkeletalMeshData
 *
 * Non-mutable data asset that contains properties used to define a modular mesh.
 */
UCLASS( BlueprintType, Const, Meta = ( DisplayName = "Modular skeletal mesh data", ShortTooltip = "Data asset used to define a modular skeletal mesh." ) )
class CHARACTERS_API UModularSkeletalMeshData : public UPrimaryDataAsset
{
	GENERATED_BODY()

	public:

	UPROPERTY( EditDefaultsOnly, BlueprintReadOnly, meta = ( ValidEnumValues = "MainBody, Head, Hair, Torso, Arms, Hands, Legs, Feet" ) )
	EBodyPartType MeshType;
	
	/* Some others properties */
};

/**
 * UModularStaticMeshData
 *
 * Non-mutable data asset that contains properties used to define a modular mesh.
 */
UCLASS( BlueprintType, Const, Meta = ( DisplayName = "Modular static mesh data", ShortTooltip = "Data asset used to define a modular static mesh." ) )
class CHARACTERS_API UModularStaticMeshData : public UPrimaryDataAsset
{
	GENERATED_BODY()

	public:

	UPROPERTY( EditDefaultsOnly, BlueprintReadOnly, meta = ( ValidEnumValues = "Eye, Accessory" ) )
	EBodyPartType MeshType = EBodyPartType::Eye;
	
	/* Some others properties */
};
```

UModularSkeletalMeshData instance :
![UModularSkeletalMeshData ](https://i.imgur.com/exLlMeV.png)

UModularStaticMeshData instance :
![UModularStaticMeshData](https://i.imgur.com/IdyQkls.png)

/!\ Important : for UModularStaticMeshData, the first enum byte isn't used (MainBody). If we don't declare the default value, when creating the asset, it's actually MainBody selected. But it don't appear in the list anymore if we choose a good one :
![UModularStaticMeshDataBug](https://i.imgur.com/0SkGxdD.png)

You can use my example if you're lazy to reproduce it for the doc. :)

**Comment by benui-dev** [comment]
@0ne3y3 I tried this with 5.1 retail and can't find ValidEnumNames, I wonder if it's something super new?

**Comment by 0ne3y3** [comment]
Oh didn't know InvalidEnumValues, seems better for my first case.

**Comment by benui-dev** [comment]
This is in the docs, i think i just forgot to close it
