### ISSUE TITLE
Note UFUNCTION(meta=(BlueprintAutocast)) Requirements

### ISSUE THREAD

**Issue by uextm** [benui-dev/UE-Specifier-Docs#30]
BlueprintAutocast requires the function to be static, public, BlueprintPure, have at least 1 input, and have a return output.
Only the first input will be considered for auto conversion, but you can have multiple.

These requirements are checked in EdGraphSchema_K2.cpp
https://github.com/EpicGames/UnrealEngine/blob/072300df18a94f18077ca20a14224b5d99fee872/Engine/Source/Editor/BlueprintGraph/Private/EdGraphSchema_K2.cpp#L2440

**Comment by benui-dev** [comment]
@uextm Thank you for this
