### ISSUE TITLE
UPROPERTY: Adding "AllowedTypes" example and explanation for FPrimaryAssetID

### ISSUE THREAD

**Issue by YawLighthouse** [benui-dev/UE-Specifier-Docs#8]
In AllowedTypes, the engine and available documentation states that it it only works with `FSoftObjectPath`(which should also explain that it works with `TSoftObjectPtr` & `TSoftClassPtr`), `ComponentReference`, and `UClass`(& `TSubclassOf`) properties. But it does not explain that it also can be used with `FPrimaryAssetID` which it can! The way it is used is slightly different than the example code explains, which instead uses `FPrimaryAssetType` instead of the actual object's class name(without Unreal naming prefix).

### Example Code:
The class to use with `AllowedTypes`
```c++
UCLASS()
class UYourAssetName : public UPrimaryDataAsset
{
    UYourAssetName()
    { 
        AssetType = TEXT("FancyAssetName"); 
    }

    //...
}
```

The variable declaration in another class(or maybe within the same class!)
```c++
UPROPERTY(meta = (AllowedTypes = "FancyAssetName"))
FPrimaryAssetId FancyAsset;

// Affects any primary asset ID's in the TMap
UPROPERTY(meta = (AllowedTypes = "FancyAssetName"))
TMap<FGameplayTag, FPrimaryAssetId> FancyAssetMap;
```

Pull Request for reference: https://github.com/benui-dev/UE-Specifier-Docs/pull/10

**Comment by benui-dev** [comment]
Fixed in PR #10 by @YawLighthouse, thanks!
