### ISSUE TITLE
GetPlantTypeNames sample function needs ()

### ISSUE THREAD

**Issue by sirjofri** [benui-dev/UE-Specifier-Docs#9]
https://github.com/benui-dev/UE-Specifier-Docs/blob/5d4688659d2c99826a8f05503743d79a474bc0f9/yaml/uproperty.yml#L772

Quite a small bug, basically a typo, but the UFUNCTION `GetPlantTypeNames` in the referenced line needs `()` to be a proper function.

**Comment by benui-dev** [comment]
Fixed in 5de4cc6, thanks @sirjofri!
